name: ant-design/ant-design-pro
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version:
        - 16.x
        - 14.x
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - run: echo ${{github.ref}}
    - run: npm install
    - run: yarn run lint
    - run: yarn run tsc
    - run: yarn run build
      env:
        CI: true
        PROGRESS: none
        NODE_ENV: test
        NODE_OPTIONS: --max_old_space_size=4096
