name: apache/freemarker
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  build:
    strategy:
      matrix:
        os:
        - windows-latest
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    concurrency: main_tests_${{ github.ref }}
    steps:
    - name: Welcome Message
      run: 'echo "Started with parameters: ${{ matrix.os }} because ${{ github.event_name }} on ${{ github.ref }}"'
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: 16
        distribution: zulu
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: oracle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.1.0
    - name: Run Build
      id: build_step
      run: ./gradlew "-Pfreemarker.signMethod=none" "-Pfreemarker.allowUnsignedReleaseBuild=true" --continue clean build
    - name: Upload Failed Report
      uses: actions/upload-artifact@v2.3.1
      if: failure() && steps.build_step.outcome == 'failure'
      with:
        name: test-reports-${{ matrix.os }}
        path: build/reports/**
        retention-days: 30
