name: apache/kafka
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install -r docker/requirements.txt
    - name: Build Docker Official Image Artifact
      working-directory: ./docker
      run: |
        python prepare_docker_official_image_source.py -type=${{ github.event.inputs.image_type }} -v=${{ github.event.inputs.kafka_version }}
    - name: Upload Docker Official Image Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.kafka_version }}
        path: docker/docker_official_images/${{ github.event.inputs.kafka_version }}
