name: Checkout Public Repo, build and run test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ts
    strategy:
      matrix:
        node-version: [18.x]

    steps:    
    - name: Checkout public repository
      uses: actions/checkout@v4
      with:
        repository: Azure/azure-functions-nodejs-samples
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run lint
