name: Checkout Public Repo, build and run test

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [18.x]

    steps:    
    - name: Checkout public repository
      uses: actions/checkout@v4
      with:
        repository: microsoft/sample-app-aoai-chatGPT
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: set NODE_OPTIONS=--max_old_space_size=8192
    - run: npm run build --if-present
    - run: npm run test --if-present
