name: CommunityToolkit/Maui
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  dotnet-format:
    runs-on: windows-latest
    steps:
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}
        repository: ${{ github.event.inputs.repoName }}
    - name: Run dotnet format
      id: format
      uses: jfversluis/dotnet-format@v1.0.5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        action: fix
        workspace: samples/CommunityToolkit.Maui.Sample.sln
    - name: Commit files
      if: steps.format.outputs.has-changes == 'true'
      run: |
        git config --local user.name "github-actions[bot]"

        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git commit -a -m 'Automated dotnet-format update'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: '[housekeeping] Automated PR to fix formatting errors'
        body: >
          Automated PR to fix formatting errors
        committer: GitHub <noreply@github.com>
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        labels: approved
        assignees: jfversluis
        reviewers: jfversluis, brminnick
        branch: housekeeping/fix-codeformatting
