name: Code Execution - synthetic - dotnet

on:
   workflow_dispatch:
    inputs:
      test:
        description: 'Base64 encoded JSON blob of test files'
        required: false
        default: ''
      source:
        description: 'Base64 encoded JSON blob of files to be tested'
        required: false
        default: ''

jobs:
  run-CodeSnippet:
    runs-on: ubuntu-latest
    container:
      #image: mcr.microsoft.com/vscode/devcontainers/universal:2-linux  # Specify your container image
      image: mcr.microsoft.com/vscode/devcontainers/dotnet:8.0  # Specify your container image
      options: --privileged  # Optional: Use if your container needs privileged mode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Decode the source files and test files and save them to the source/ and test/ folder
      
      - name: Unpack source and test files
        shell: bash
        run: |
              # Write a Python script to expand base 64 encoded JSON file system
              # into individual files in a "bin" directory.
              SOURCE="${{ github.event.inputs.source }}"
              TEST="${{ github.event.inputs.test }}"

              cat << 'EOF' > fileSystemExpansion.py
              import sys
              import os
              import base64
              import json

              def main():
                  output_dir = sys.argv[1]
                  encoded_json = sys.argv[2]
                  decoded_json = base64.b64decode(encoded_json).decode('utf-8')
                  file_system = json.loads(decoded_json)

                  os.makedirs(output_dir, exist_ok=True)

                  for file_name, file_content in file_system.items():
                      file_path = os.path.join(output_dir, file_name)
                      with open(file_path, 'w') as file:
                          file.write(file_content)

              if __name__ == "__main__":
                 main()
              EOF

              python3 fileSystemExpansion.py source "$SOURCE"
              python3 fileSystemExpansion.py test "$TEST"



      - name: Run code snippet (ces)
        shell: bash
        run: |

      - name: Run code (ces)
        shell: bash
        run: |
              export PATH="$PATH:/github/home/.dotnet/tools"
              cd cs
              cat << 'EOF' > Program.cs
              ${{ env.CODE }}
              EOF
              echo "Doing build:"
              echo "========================"
              dotnet build
              echo  "======================="
              cd bin/Debug/net8.0
              echo "Running code:"
              echo  "======================="
              dotnet ConsoleApp.dll

              echo "========================"
              echo "!!== RUN COMPLETED ==!!"
              echo "End devContainer run"

