name: dotnet/winforms
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions:
  issues: write
  pull-requests: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        path: ./actions
        ref: ${{ github.event.inputs.ref }}
    - name: Install Actions
      run: npm install --production --prefix ./actions
    - name: Run Locker
      uses: ./actions/locker
      with:
        daysSinceClose: ${{ fromJson(inputs.daysSinceClose  || 30) }}
        daysSinceUpdate: ${{ fromJson(inputs.daysSinceUpdate || 30) }}
