name: dotnet/runtime
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  compare_repos:
    if: true
    name: Sync Code
    runs-on: windows-latest
    steps:
    - name: Checkout aspnetcore
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        path: aspnetcore
        ref: ${{ github.event.inputs.ref }}
    - name: Checkout runtime
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        path: runtime
        ref: ${{ github.event.inputs.ref }}
    - name: Copy
      shell: cmd
      working-directory: .\aspnetcore\src\Shared\runtime\
      env:
        RUNTIME_REPO: d:\a\runtime\runtime\runtime\
      run: CopyToRuntime.cmd
    - name: Diff
      shell: cmd
      working-directory: .\runtime\
      run: |
        mkdir ..\artifacts

        git status > ..\artifacts\status.txt

        git diff > ..\artifacts\diff.txt
    - uses: actions/upload-artifact@v4
      with:
        name: results
        path: artifacts
    - name: Check
      id: check
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $changed = .\runtime\.github\workflows\aspnetcore-sync-checkdiff.ps1

        echo "::set-output name=changed::$changed"
    - name: Send PR
      if: steps.check.outputs.changed == 'true'
      uses: dotnet/actions-create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: .\runtime
        commit-message: Sync shared code from aspnetcore
        title: Sync shared code from aspnetcore
        body: This PR was automatically generated to sync shared code changes from aspnetcore. Fixes https://github.com/dotnet/aspnetcore/issues/18943
        labels: area-System.Net.Http
        base: main
        branch: github-action/sync-aspnetcore
        branch-suffix: timestamp
