name: dotnet/aspire
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
jobs:
  backport:
    if: true
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main
    with:
      pr_description_template: >
        Backport of #%source_pr_number% to %target_branch%


        /cc %cc_users%


        ## Customer Impact


        ## Testing


        ## Risk


        ## Regression?
