name: dotnet/wpf
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
jobs:
  backport:
    if: true
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main
    with:
      pr_description_template: >
        Backport of #%source_pr_number% to %target_branch%

        /cc %cc_users%

        ## Customer Impact

        ## Testing

        ## Risk

        **IMPORTANT**: If this backport is for a servicing release, please verify that:

        - The PR target branch is `release/X.0-staging`, not `release/X.0`.

        - If the change touches code that ships in a NuGet package, you have added the necessary [package authoring](https://github.com/dotnet/runtime/blob/main/docs/project/library-servicing.md) and gotten it explicitly reviewed.
