name: Run Dev Container - Code Execution - go

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Base64 encoded code snippet'
        required: false
        default: ''
      testInput:
        description: 'test input'
        required: false
        default: ''
      expectedOutput:
        description: 'expected output from the code for test input'
        required: false
        default: ''
        
jobs:
  run-devcontainer:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/go
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode code snippet
        shell: bash
        run: |
         if [ -n "${{ github.event.inputs.code }}" ]; then
           echo "Start decoding code"
           echo "${{ github.event.inputs.code }}"
           echo "${{ github.event.inputs.code }}" | base64 --decode | sed 's/\r$//' > codeFile
           echo "Writing code content:"
           {
               echo 'CODE<<EOF'
               cat codeFile
               echo EOF
           } >> $GITHUB_ENV
         fi
      
      - name: Print env values for debugging
        shell: bash
        run: |
             echo "=====Custom command:"
             echo "${{ env.CODE }}"
      
      - name: Run code (ces)
        shell: bash
        run: |
          cat << 'EOF' > code.go
          ${{ env.CODE }}
          EOF
          echo "Running custom command:"
          echo "========================"
          go run code.go
          echo "========================"
          echo "!!== RUN COMPLETED ==!!"
          echo "End devContainer run"