name: google/guice
env:
  USE_BAZEL_VERSION: 7.1.1
  USE_JAVA_DISTRIBUTION: zulu
  USE_JAVA_VERSION: 11
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
concurrency:
  group: ${{ (github.ref == 'refs/heads/master') && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true
jobs:
  maven-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        java:
        - 11
        - 17
        - 21
        include:
        - os: macos-latest
          java: 17
      fail-fast: false
      max-parallel: 4
    name: Test using Maven with JDK ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: ./.github/actions/maven-test
  bazel-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        java:
        - 11
        - 17
        - 21
        include:
        - os: macos-latest
          java: 17
      fail-fast: false
      max-parallel: 4
    name: Test using Bazel with JDK ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: ./.github/actions/bazel-test
  bazel-build:
    runs-on: ubuntu-latest
    name: Bazel Build
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: ./.github/actions/bazel-build
  local-artifact-tests:
    runs-on: ubuntu-latest
    needs:
    - bazel-build
    name: Local Artifact Tests
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: ./.github/actions/local-artifact-tests
  publish:
    runs-on: ubuntu-latest
    needs:
    - maven-test
    - bazel-test
    - bazel-build
    - local-artifact-tests
    if: true
    name: Publish Javadoc and Snapshot
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: ./.github/actions/publish-snapshot
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
