name: jenkey2011/vuepress-deploy
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
    - uses: Actions-R-Us/actions-tagger@latest
      with:
        publish_latest: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
