name: junit-team/junit4
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions:
  contents: read
jobs:
  build-and-verify:
    name: Build and verify (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Download Maven
      run: ./mvnw --version
    - name: Set up JDK 6
      if: ${{ matrix.java == '6'}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Set up JDK
      if: ${{ matrix.java != '6'}}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: maven
    - name: Build and verify
      run: ./mvnw verify javadoc:javadoc site:site --batch-mode --errors --settings .github/workflows/settings.xml
  publish-snapshots:
    name: Publish snapshot artifacts
    if: true
    needs: build-and-verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Download Maven
      run: ./mvnw --version
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Publish snapshot artifacts
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: ./mvnw deploy --batch-mode --errors --activate-profiles generate-docs --settings .github/workflows/settings.xml
