name: machty/ember-maybe-import-regenerator
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  test:
    timeout-minutes: 10
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: volta-cli/action@v1
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test
  floating-dependencies:
    timeout-minutes: 10
    name: Floating Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: volta-cli/action@v1
    - run: yarn install --no-lockfile
    - run: yarn test
