name: microsoft/vscode-python
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
env:
  TRIAGERS: '["karrtikr","karthiknadig","paulacamargo25","eleanorjboyd", "brettcannon","anthonykim1"]'
permissions:
  issues: write
jobs:
  add_label:
    runs-on: ubuntu-latest
    if: true
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
        path: ./actions
    - name: Install Actions
      run: npm install --production --prefix ./actions
    - name: Add "info-needed" label
      uses: ./actions/python-triage-info-needed
      with:
        triagers: ${{ env.TRIAGERS }}
        action: add
        token: ${{secrets.GITHUB_TOKEN}}
  remove_label:
    if: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
        path: ./actions
    - name: Install Actions
      run: npm install --production --prefix ./actions
    - name: Remove "info-needed" label
      uses: ./actions/python-triage-info-needed
      with:
        triagers: ${{ env.TRIAGERS }}
        action: remove
        token: ${{secrets.GITHUB_TOKEN}}
