name: mui-org/material-ui
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions: {}
jobs:
  test-dev:
    if: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
    steps:
    - run: echo "${{ github.actor }}"
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        fetch-depth: 0
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Set up pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
    - name: Use Node.js 18.x
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
      with:
        node-version: 18
        cache: pnpm
    - run: pnpm install
    - run: pnpm build:ci
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: pnpm release:changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: pnpm validate-declarations
    - name: pnpm release:tag
      run: |
        git remote -v

        pnpm release:tag --dryRun
