name: netty/netty
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
permissions: read-all
env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240
jobs:
  stage-snapshot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - setup: linux-x86_64-java8
          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml build
          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml run stage-snapshot
        - setup: linux-aarch64
          docker-compose-build: -f docker/docker-compose.centos-7.yaml build
          docker-compose-run: -f docker/docker-compose.centos-7.yaml run cross-compile-aarch64-stage-snapshot
        - setup: linux-riscv64
          docker-compose-build: -f docker/docker-compose.ubuntu-20.04.yaml build
          docker-compose-run: -f docker/docker-compose.ubuntu-20.04.yaml run cross-compile-riscv64-stage-snapshot
    name: stage-snapshot-${{ matrix.setup }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Cache local Maven repository
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ matrix.setup }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: >
          ${{ runner.os }}-maven-${{ matrix.setup }}-

          ${{ runner.os }}-maven-
    - name: Create local staging directory
      run: mkdir -p ~/local-staging
    - name: Build docker image
      run: docker-compose ${{ matrix.docker-compose-build }}
    - name: Stage snapshots to local staging directory
      run: docker-compose ${{ matrix.docker-compose-run }}
    - name: Upload local staging directory
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.setup }}-local-staging
        path: ~/local-staging
        if-no-files-found: error
  deploy-staged-snapshots:
    runs-on: ubuntu-latest
    needs: stage-snapshot
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - name: Cache local Maven repository
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-deploy-staged-snapshots-${{ hashFiles('**/pom.xml') }}
        restore-keys: >
          ${{ runner.os }}-maven-deploy-staged-snapshots-

          ${{ runner.os }}-maven-
    - name: Prepare environment variables
      run: |
        echo "LOCAL_STAGING_DIR=$HOME/local-staging" >> $GITHUB_ENV
    - name: Download linux-aarch64 staging directory
      uses: actions/download-artifact@v4
      with:
        name: linux-aarch64-local-staging
        path: ~/linux-aarch64-local-staging
    - name: Download linux-riscv64 staging directory
      uses: actions/download-artifact@v4
      with:
        name: linux-riscv64-local-staging
        path: ~/linux-riscv64-local-staging
    - name: Download linux-x86_64-java8 staging directory
      uses: actions/download-artifact@v4
      with:
        name: linux-x86_64-java8-local-staging
        path: ~/linux-x86_64-java8-local-staging
    - name: Merge staging repositories
      run: |
        mkdir -p ~/local-staging/deferred

        cat ~/linux-aarch64-local-staging/deferred/.index >>  ~/local-staging/deferred/.index

        cp -r ~/linux-aarch64-local-staging/deferred/* ~/local-staging/deferred/

        cat ~/linux-riscv64-local-staging/deferred/.index >>  ~/local-staging/deferred/.index

        cp -r ~/linux-riscv64-local-staging/deferred/* ~/local-staging/deferred/

        cat ~/linux-x86_64-java8-local-staging/deferred/.index >>  ~/local-staging/deferred/.index

        cp -r ~/linux-x86_64-java8-local-staging/deferred/* ~/local-staging/deferred/
    - uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: >
          [{
            "id": "sonatype-nexus-snapshots",
            "username": "${{ secrets.SONATYPE_USERNAME }}",
            "password": "${{ secrets.SONATYPE_PASSWORD }}"
          }]
    - name: Deploy local staged artifacts
      run: ./mvnw -B --file pom.xml org.sonatype.plugins:nexus-staging-maven-plugin:deploy-staged -DaltStagingDirectory=$LOCAL_STAGING_DIR
