name: nodejs/node
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
concurrency: ${{ github.workflow }}
env:
  NODE_VERSION: lts/*
permissions:
  contents: read
jobs:
  get-prs-for-ci:
    permissions:
      pull-requests: read
    if: true
    runs-on: ubuntu-latest
    outputs:
      numbers: ${{ steps.get_prs_for_ci.outputs.numbers }}
    steps:
    - name: Get Pull Requests
      id: get_prs_for_ci
      run: |
        numbers=$(gh pr list \
                --repo ${{ github.repository }} \
                --label 'request-ci' \
                --json 'number' \
                -t '{{ range . }}{{ .number }} {{ end }}' \
                --limit 5)
        echo "numbers=$numbers" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  start-ci:
    permissions:
      contents: read
      pull-requests: write
    needs: get-prs-for-ci
    if: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        persist-credentials: false
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Install Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install @node-core/utils
      run: npm install -g @node-core/utils
    - name: Setup @node-core/utils
      run: |
        ncu-config set username ${{ secrets.JENKINS_USER }}

        ncu-config set token "${{ secrets.GH_USER_TOKEN }}"

        ncu-config set jenkins_token ${{ secrets.JENKINS_TOKEN }}

        ncu-config set owner "${{ github.repository_owner }}"

        ncu-config set repo "$(echo ${{ github.repository }} | cut -d/ -f2)"
    - name: Start the CI
      run: ./tools/actions/start-ci.sh ${{ needs.get-prs-for-ci.outputs.numbers }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
