name: OfficeDev/teams-toolkit
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  verify-constraints:
    name: verify-constraints
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: pnpm/action-setup@v4
    - name: Setup project
      run: |
        pnpm --filter=templates install
    - name: Verify
      run: |
        npm run verify
      working-directory: ./templates
