name: openai/openai-python
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  release:
    name: release
    if: true
    runs-on: ubuntu-latest
    environment: publish
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: stainless-api/trigger-release-please@v1
      id: release
      with:
        repo: ${{ github.event.repository.full_name }}
        stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}
    - name: Install Rye
      if: ${{ steps.release.outputs.releases_created }}
      run: |
        curl -sSf https://rye.astral.sh/get | bash

        echo "$HOME/.rye/shims" >> $GITHUB_PATH
      env:
        RYE_VERSION: 0.35.0
        RYE_INSTALL_OPTION: --yes
    - name: Publish to PyPI
      if: ${{ steps.release.outputs.releases_created }}
      run: |
        bash ./bin/publish-pypi
      env:
        PYPI_TOKEN: ${{ secrets.OPENAI_PYPI_TOKEN || secrets.PYPI_TOKEN }}
