name: swebench-psf-requests

on:
   workflow_dispatch:
    inputs:
      patch:
        description: 'Base64 encoded patch file'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-22.04]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: psf/requests        
    - name: Decode and apply patch
      run: |
          if [ -n "${{ github.event.inputs.patch }}" ]; then
            echo "Patch input provided. Applying patch..."
            echo "${{ github.event.inputs.patch }}" | base64 --decode
             echo "Creating patch file..."
            echo "${{ github.event.inputs.patch }}" | base64 --decode  > patch.diff           
            echo "Decoded patch content:"
            cat patch.diff  # Display the patch content for debugging
            # Check the patch without applying it and capture the output
            git apply --check patch.diff --verbose 2>&1 || {
              echo "Patch does not apply cleanly. Showing patch check results:"
              git apply --check patch.diff --verbose 2>&1
              exit 1
            }

            # Apply the patch
            git apply patch.diff || {
              echo "Failed to apply patch"
              exit 1
            }
          else
            echo "No patch input provided. Skipping patch application."
          fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        make
    - name: Run tests
      run: |
        make ci
