name: qos-ch/logback
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
concurrency:
  group: ${{ (github.ref == 'refs/heads/branch_1.2.18' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  Test:
    name: JDK ${{ matrix.jdk }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk:
        - 21
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      fail-fast: true
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 50
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - name: Set up Java ${{ matrix.jdk }}
      if: ${{ matrix.jdk != '8' }}
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - name: Install
      run: mvn -B install
