name: redwoodjs/github-bot
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
jobs:
  redwood-project-ci:
    name: "\U0001F332 Redwood CI"
    runs-on: ubuntu-latest
    steps:
    - name: "\U0001F332 Redwood CI"
      uses: redwoodjs/project-ci-action@v0.1.1
