name: redwoodjs/deploy-target-ci
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  REDWOOD_CI: 1
jobs:
  ci:
    name: "\U0001F504 CI"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
        - ./baremetal
        - ./coherence
        - ./flightcontrol
        - ./netlify
        - ./render-postgres
        - ./vercel
      fail-fast: false
    steps:
    - name: "\U0001F504 CI / ${{ matrix.project }}"
      uses: redwoodjs/project-ci-action@main
      with:
        project-directory: ${{ matrix.project }}
        run-lint: false
