name: starbeamjs/starbeam
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: Name of the repo
        required: false
      patch:
        description: Base64 encoded patch content
        required: false
      command:
        description: Command to run
        required: false
      ref:
        description: The repo branch, tag, or commit SHA to checkout
        required: false
concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: the-starbeam-folks
jobs:
  install_dependencies:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: wyvox/action-setup-pnpm@v3
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
    - install_dependencies
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: wyvox/action-setup-pnpm@v3
    - run: pnpm build
    - name: Ensure Certain dependencies don't end up in the production bundles
      run: node ./workspace/scripts/build-verify.js
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs:
    - install_dependencies
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: wyvox/action-setup-pnpm@v3
    - run: pnpm ci:specs
  test_prod:
    name: Tests (production)
    runs-on: ubuntu-latest
    needs:
    - install_dependencies
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.repoName }}
        ref: ${{ github.event.inputs.ref }}
    - uses: wyvox/action-setup-pnpm@v3
    - run: pnpm ci:prod
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs:
    - install_dependencies
    steps:
    - uses: wyvox/action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: ./node_modules/.bin/turbo run test:types --continue
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
    - install_dependencies
    steps:
    - uses: wyvox/action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: ./node_modules/.bin/turbo run test:lint --continue
